export const PRODUCTS = [
  {
    id: "1",
    name: "Aple Kore",
    type: "noms",
    description: "A tasty half-eaten rotten apple",
    price: 130,
    image: "/images/apple-core.jpeg",
    count: 1,
    tags: ["noms"],
  },
  {
    id: "2",
    name: "Ol' Sok",
    type: "stuff",
    description:
      "A single, lightly torn sock glazed in locally sourced puddle.",
    price: 200,
    image: "/images/old-sock.png",
    count: 1,
    tags: ["stuff"],
  },
  {
    id: "3",
    name: "Dish Sponj",
    type: "thangs",
    description: "Aged and marinated in the scraps of a stainless steal sink.",
    price: 80,
    image: "/images/dish-sponge.png",
    count: 1,
    tags: ["thangs"],
  },

  {
    id: "4",
    name: "Panana Beel",
    type: "noms",
    description: "A slippery, slimy, old, blackened banana peel",
    price: 100,
    image: "/images/banana-peel.jpeg",
    count: 1,
    tags: ["noms"],
  },
  {
    id: "5",
    name: "Wet Tishue",
    type: "thangs",
    description: "A classic household tissue coated in a creamy mucus ganache.",
    price: 220,
    image: "/images/used-tissue.jpg",
    count: 1,
    tags: ["thangs"],
  },
  {
    id: "6",
    name: "Derty Boot",
    type: "stuff",
    description: "Cradle your babies in this cozy vintage boot.",
    price: 300,
    image: "/images/old-boot.jpg",
    count: 1,
    tags: ["stuff"],
  },
  {
    id: "7",
    name: "Roten Eg",
    type: "noms",
    description: "It may be rotten but it stinks so good!",
    price: 150,
    image: "/images/rotten-egg.jpg",
    count: 1,
    tags: ["noms"],
  },
  {
    id: "8",
    name: "Brokem Botle",
    type: "accs",
    description:
      "Tempered using the latest technology, these radiant shards glimmer like diamonds.",
    price: 250,
    image: "/images/broken-bottle.jpg",
    count: 1,
    tags: ["stuff"],
  },
  {
    id: "9",
    name: "Fantsy Box",
    type: "accs",
    description: "Perfect for afternoon naps away from the midday sun.",
    price: 175,
    image: "/images/broken-box.jpg",
    count: 1,
    tags: ["stuff"],
  },
  {
    id: "10",
    name: "Bone Komb",
    type: "thangs",
    description: "Never have a bad fur-day again with this contemporary comb.",
    price: 120,
    image: "/images/fish-bone.webp",
    count: 1,
    tags: ["thangs"],
  },
];

